import { NextRequest, NextResponse } from "next/server";

// Protect admin routes and disable prefetch responses for unauthenticated clients.
export function proxy(req: NextRequest) {
  const { pathname } = req.nextUrl;

  // Only guard admin routes.
  if (!pathname.startsWith("/admin")) return NextResponse.next();

  // Detect common prefetch headers generated by Next.js during Link prefetching.
  const isPrefetch =
    req.headers.get("purpose") === "prefetch" ||
    req.headers.has("next-router-prefetch");

  const isLocalhost =
    req.nextUrl.hostname === "localhost" ||
    req.nextUrl.hostname === "127.0.0.1";
  const prefix = isLocalhost ? "" : "__Host-";
  const tokenName = `${prefix}__convexAuthJWT`;

  const tokenCookie =
    req.cookies.get(tokenName) ?? req.cookies.get("__convexAuthJWT");
  const token = tokenCookie?.value ?? null;

  if (!token) {
    // For prefetch, return 401 to avoid returning content for unauthorized background fetches.
    if (isPrefetch) {
      return new Response(null, { status: 401 });
    }

    // Redirect unauthorized users to admin sign-in or intruder page depending on your preference.
    // Using /admin as sign-in location keeps user flow consistent.
    const signInUrl = new URL("/admin", req.nextUrl);
    return NextResponse.redirect(signInUrl);
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/admin/:path*"],
};
