import { NextRequest, NextResponse } from "next/server";
import { getAuthToken } from "@/lib/get-auth-token";

// Protect admin routes and disable prefetch responses for unauthenticated clients.
export async function proxy(req: NextRequest) {
  const { pathname } = req.nextUrl;

  // Only guard admin routes (allow access page to remain publicly accessible).
  if (!pathname.startsWith("/admin")) return NextResponse.next();
  // Allow the admin access/login page without auth to avoid redirect loops.
  if (pathname.startsWith("/admin/access")) {
    // If user is at /admin and unauthenticated show the access page instead.
    // Let the access page handle redirects or login UI.
    return NextResponse.next();
  }

  // Detect common prefetch headers generated by Next.js during Link prefetching.
  const isPrefetch =
    req.headers.get("purpose") === "prefetch" ||
    req.headers.has("next-router-prefetch");

  // Short-circuit prefetching to avoid reading cookies and prevent unnecessary work.
  if (isPrefetch) return new Response(null, { status: 401 });

  // Retrieve token after prefetch checks — this uses Next.js cookie store safely.
  let token: string | undefined = undefined;
  try {
    token = await getAuthToken();
  } catch {
    token = undefined;
  }

  if (!token) {
    // Redirect unauthorized users to the admin access (login) page.
    // Preserve requested path for optional redirect after sign-in.
    const signInUrl = new URL("/admin/access", req.nextUrl);
    signInUrl.searchParams.set(
      "redirect",
      req.nextUrl.pathname + req.nextUrl.search
    );
    return NextResponse.redirect(signInUrl);
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/admin/:path*"],
};
